<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_Excercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7).

In [2]:
import torch
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.0064, 0.9653, 0.1863, 0.4682, 0.7394, 0.1892, 0.8644],
        [0.5751, 0.6476, 0.4276, 0.4708, 0.8928, 0.9649, 0.9617],
        [0.5123, 0.3654, 0.3792, 0.2408, 0.9235, 0.8363, 0.4763],
        [0.8051, 0.1505, 0.9733, 0.8059, 0.1898, 0.1320, 0.1160],
        [0.8893, 0.7497, 0.3312, 0.2410, 0.7046, 0.8596, 0.8203],
        [0.8914, 0.1101, 0.8500, 0.2224, 0.5297, 0.2524, 0.8517],
        [0.6406, 0.9706, 0.8707, 0.1009, 0.0378, 0.0578, 0.0483]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
rand_tensor_b = torch.rand(1,7)
torch.matmul(rand_tensor, rand_tensor_b.T)

tensor([[1.6435],
        [2.2858],
        [1.6329],
        [1.2726],
        [1.9279],
        [1.3539],
        [0.8017]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [4]:
RAND_SEED = 36;
torch.manual_seed(RAND_SEED)
rand_tensor = torch.rand(7,7)
torch.manual_seed(RAND_SEED)
rand_tensor_b = torch.rand(1,7)
torch.matmul(rand_tensor, rand_tensor_b.T)

tensor([[1.7185],
        [2.0795],
        [0.9848],
        [1.6041],
        [1.3208],
        [2.0223],
        [1.9024]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"
RAND_SEED = 1234;
torch.manual_seed(RAND_SEED)
rand_gpu_tensor = torch.rand(7,7, device = device);
rand_gpu_tensor

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [15]:
RAND_SEED = 1234;
torch.manual_seed(RAND_SEED)
random_tensor_a = torch.rand(2,3)
torch.manual_seed(RAND_SEED)
random_tensor_b = torch.rand(2,3)
random_tensor_a_GPU = random_tensor_a.to(device=device)
random_tensor_b_GPU = random_tensor_b.to(device=device)
print(random_tensor_a_GPU)
print(random_tensor_b_GPU)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [19]:
dot_product = torch.matmul(random_tensor_a_GPU, random_tensor_b_GPU.T)
dot_product

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7

In [20]:
dot_product_max = torch.max(dot_product)
dot_product_min = torch.min(dot_product)
print(f"Max -> {dot_product_max}, Min -> {dot_product_min}")

Max -> 0.628727912902832, Min -> 0.21611443161964417


9. Find the maximum and minimum index values of the output of 7.

In [21]:
dot_product_max_index = torch.argmax(dot_product)
dot_product_min_index = torch.argmin(dot_product)
print(f"Max Index -> {dot_product_max_index}, Min Index -> {dot_product_min_index}")

Max Index -> 3, Min Index -> 1


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [26]:
RAND_SEED = 10
torch.manual_seed(RAND_SEED)
rand_tensor = torch.rand(1,1,1,10)
squeezed_rand_tensor = rand_tensor.squeeze()
print(f"Original tensor -> {rand_tensor} with shape -> {rand_tensor.shape}")
print(f"Modified tensor -> {squeezed_rand_tensor} with shape -> {squeezed_rand_tensor.shape}")

Original tensor -> tensor([[[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
           0.6178, 0.3304]]]]) with shape -> torch.Size([1, 1, 1, 10])
Modified tensor -> tensor([0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693, 0.6178,
        0.3304]) with shape -> torch.Size([10])


good refresher of scalars, vectors, matrices here https://www.youtube.com/watch?v=f5liqUk0ZTw