<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

## Understanding Scalars, vectors, matrices and tensors

In [8]:
#scalar
scalar = torch.tensor(7)
print(f"scalar = { scalar } \nndim -> {scalar.ndim} shape -> {scalar.shape} item -> {scalar.item()}")

scalar = 7 
ndim -> 0 shape -> torch.Size([]) item -> 7


In [10]:
## Vector
vector = torch.tensor([7,7])
print(f"Vector = { vector } \nndim -> {vector.ndim} shape -> {vector.shape}")

Vector = tensor([7, 7]) 
ndim -> 1 shape -> torch.Size([2])


In [15]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
print(f"Matrix = { MATRIX } \nndim -> {MATRIX.ndim} shape -> {MATRIX.shape}")

Matrix = tensor([[ 7,  8],
        [ 9, 10]]) 
ndim -> 2 shape -> torch.Size([2, 2])


The torch.size indicates the shape of a tensor, and describes the number of elements along each dimension. In the case of a tensor t with shape (2, 4, 3) as below, it means that the tensor has 3 dimensions, with the first dimension having a size of 2, the second dimension having a size of 4, and the third dimension having a size of 3. In other words, the tensor has 2 rows, each row has 4 columns, and each column has 3 elements. The total number of elements in the tensor is the product of the sizes of all dimensions, which in this case is 2 * 4 * 3 = 24

In [24]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91],
        [101,111,121]
    ]
    ])
print(f"Tensor = { TENSOR } \nndim -> {TENSOR.ndim} shape -> {TENSOR.shape} totalElements -> {TENSOR.numel()}")

Tensor = tensor([[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9],
         [ 10,  11,  12]],

        [[ 11,  21,  31],
         [ 41,  51,  61],
         [ 71,  81,  91],
         [101, 111, 121]]]) 
ndim -> 3 shape -> torch.Size([2, 4, 3]) totalElements -> 24


## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3925, 0.5479, 0.7167, 0.0171],
        [0.3665, 0.0812, 0.2435, 0.9365],
        [0.0105, 0.6657, 0.4015, 0.2379]])

In [ ]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.6814, 0.4215, 0.9989],
         [0.4260, 0.1123, 0.9649],
         [0.7073, 0.6121, 0.0493],
         ...,
         [0.1358, 0.9448, 0.8307],
         [0.6886, 0.1669, 0.7858],
         [0.8664, 0.8043, 0.6006]],

        [[0.2608, 0.4805, 0.6922],
         [0.9359, 0.4109, 0.0077],
         [0.0800, 0.3225, 0.2348],
         ...,
         [0.4824, 0.1389, 0.7154],
         [0.5431, 0.1958, 0.7504],
         [0.9450, 0.0463, 0.2313]],

        [[0.8350, 0.6308, 0.2388],
         [0.7125, 0.7378, 0.1595],
         [0.3496, 0.5267, 0.5192],
         ...,
         [0.6217, 0.2468, 0.6909],
         [0.4355, 0.3996, 0.7647],
         [0.2897, 0.6720, 0.4996]],

        ...,

        [[0.1857, 0.8646, 0.9807],
         [0.2316, 0.4323, 0.0396],
         [0.7113, 0.1904, 0.3750],
         ...,
         [0.5556, 0.9130, 0.2981],
         [0.4410, 0.5012, 0.2330],
         [0.8252, 0.1715, 0.5066]],

        [[0.2903, 0.8105, 0.3000],
         [0.3948, 0.9021, 0.4847],
         [0.

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [ ]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [ ]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [ ]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.3060, 0.3503, 0.5050, 0.3769],
        [0.3169, 0.3407, 0.6303, 0.2156],
        [0.3727, 0.2785, 0.0234, 0.8448]])

In [ ]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.3060, 0.3503, 0.5050, 0.3769],
        [0.3169, 0.3407, 0.6303, 0.2156],
        [0.3727, 0.2785, 0.0234, 0.8448]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [ ]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])

## Transposing tensors

In [ ]:
## Transpose
tensor = torch.tensor([[1,2,3]])
print(f"Original Tensor -> {tensor}, size -> {tensor.shape}")
transposed_Tensor = tensor.T
print(f"Transposed Tensor -> {transposed_Tensor}, size -> {transposed_Tensor.shape}")

Original Tensor -> tensor([[1, 2, 3]]), size -> torch.Size([1, 3])
Transposed Tensor -> tensor([[1],
        [2],
        [3]]), size -> torch.Size([3, 1])


## Aggregations (min, max, sum ...)

In [ ]:
## create tensor
x = torch.arange(0, 100, 10)
print(x)
x_min = torch.min(x) # or you can just use x.min() ...ditto for the rest
x_min_position = torch.argmin(x)
x_max = torch.max(x)
x_max_position = torch.argmax(x)
x_mean = torch.mean(x.to(torch.float64)) # note here that mean can not work on integers
x_total = torch.sum(x)
print(f"min -> {x_min}, position -> {x_min_position}, \nmax -> {x_max}, position -> {x_max_position}, \nave -> {x_mean}, \ntotal -> {x_total}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min -> 0, position -> 0, 
max -> 90, position -> 9, 
ave -> 45.0, 
total -> 450


## Reshaping, stacking, squeezing and unsqueezing tensors



*   Reshaping - given an input tensor, change to defined shape
*   View - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* Stacking - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* Squeeze - Squeezes input to remove all the dimenions with value 1.
* UnSqueeze - Returns input with a dimension value of 1 added at dim.
* Permute - Returns a view of the original input with its dimensions permuted (rearranged) to dims



In [ ]:
## Reshaping - add an extra dimension
x = torch.arange(1,10)
print(x, x.shape)
## note that new dimensions must be congruent with the shape we want to change or will error, TODO: play around with this
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [ ]:
## Change the view
x = torch.arange(1,10)
print(x, x.shape)
# same as reshape, however this shares the same memory as the original tensor, so if you change z then x will change as well
z = x.view(1, 9)
print(z, z.shape)
## example of the mutation carrying on to the original tensor
z[0][3] = 19
print(z, z.shape)
print(x, x.shape) # <- note here that x changed too!

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[ 1,  2,  3, 19,  5,  6,  7,  8,  9]]) torch.Size([1, 9])
tensor([ 1,  2,  3, 19,  5,  6,  7,  8,  9]) torch.Size([9])


In [ ]:
## Stack tensors ontop of each other
x = torch.arange(1,10)
print(x, x.shape)
x_stacked = torch.stack([x, x, x], dim=0) # default
print(f"stacked default \n{x_stacked}, size={x_stacked.shape}")
x_stacked = torch.stack([x, x, x], dim=1)
print(f"stacked dim = 1 \n{x_stacked}, size={x_stacked.shape}")

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
stacked default 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]), size=torch.Size([3, 9])
stacked dim = 1 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]), size=torch.Size([9, 3])
