<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

## Understanding Scalars, vectors, matrices and tensors

In [2]:
#scalar
scalar = torch.tensor(7)
print(f"scalar = { scalar } \nndim -> {scalar.ndim} shape -> {scalar.shape} item -> {scalar.item()}")

scalar = 7 
ndim -> 0 shape -> torch.Size([]) item -> 7


In [3]:
## Vector
vector = torch.tensor([7,7])
print(f"Vector = { vector } \nndim -> {vector.ndim} shape -> {vector.shape}")

Vector = tensor([7, 7]) 
ndim -> 1 shape -> torch.Size([2])


In [4]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
print(f"Matrix = { MATRIX } \nndim -> {MATRIX.ndim} shape -> {MATRIX.shape}")

Matrix = tensor([[ 7,  8],
        [ 9, 10]]) 
ndim -> 2 shape -> torch.Size([2, 2])


The torch.size indicates the shape of a tensor, and describes the number of elements along each dimension. In the case of a tensor t with shape (2, 4, 3) as below, it means that the tensor has 3 dimensions, with the first dimension having a size of 2, the second dimension having a size of 4, and the third dimension having a size of 3. In other words, the tensor has 2 rows, each row has 4 columns, and each column has 3 elements. The total number of elements in the tensor is the product of the sizes of all dimensions, which in this case is 2 * 4 * 3 = 24

So maybe one way to think of 3 dimensions is as a cube with height (2), width (4) and depth (3)... but any more additional dims will be hard to mentally picture

In [5]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91],
        [101,111,121]
    ]
    ])
print(f"Tensor = { TENSOR } \nndim -> {TENSOR.ndim} shape -> {TENSOR.shape} totalElements -> {TENSOR.numel()}")

Tensor = tensor([[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9],
         [ 10,  11,  12]],

        [[ 11,  21,  31],
         [ 41,  51,  61],
         [ 71,  81,  91],
         [101, 111, 121]]]) 
ndim -> 3 shape -> torch.Size([2, 4, 3]) totalElements -> 24


## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [6]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0380, 0.6816, 0.7677, 0.2371],
        [0.3035, 0.8352, 0.5477, 0.7864],
        [0.2377, 0.8876, 0.0999, 0.6139]])

In [7]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.3769, 0.2870, 0.7550],
         [0.6447, 0.9894, 0.1389],
         [0.6810, 0.0209, 0.0268],
         ...,
         [0.6239, 0.1110, 0.5327],
         [0.1452, 0.8303, 0.7350],
         [0.0607, 0.0803, 0.8662]],

        [[0.0489, 0.5573, 0.5724],
         [0.6695, 0.2984, 0.4482],
         [0.3546, 0.3733, 0.4549],
         ...,
         [0.6207, 0.1141, 0.0080],
         [0.4985, 0.0222, 0.2929],
         [0.0992, 0.1858, 0.9112]],

        [[0.7332, 0.4798, 0.4842],
         [0.8212, 0.0051, 0.1345],
         [0.3149, 0.4148, 0.8103],
         ...,
         [0.1112, 0.6681, 0.8620],
         [0.6931, 0.1210, 0.5059],
         [0.8922, 0.0557, 0.0192]],

        ...,

        [[0.6936, 0.5569, 0.6055],
         [0.7899, 0.0576, 0.4908],
         [0.9540, 0.2762, 0.4130],
         ...,
         [0.4598, 0.4090, 0.6466],
         [0.6536, 0.6144, 0.2459],
         [0.5586, 0.3532, 0.8807]],

        [[0.4233, 0.5614, 0.3225],
         [0.6378, 0.6731, 0.9062],
         [0.

In [8]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [9]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [11]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [13]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [14]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [15]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.2922, 0.5967, 0.9741, 0.9865],
        [0.7208, 0.8729, 0.7215, 0.2149],
        [0.0678, 0.6781, 0.9016, 0.3256]])

In [16]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.2922, 0.5967, 0.9741, 0.9865],
        [0.7208, 0.8729, 0.7215, 0.2149],
        [0.0678, 0.6781, 0.9016, 0.3256]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [18]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])

## Transposing tensors

In [19]:
## Transpose
tensor = torch.tensor([[1,2,3]])
print(f"Original Tensor -> {tensor}, size -> {tensor.shape}")
transposed_Tensor = tensor.T
print(f"Transposed Tensor -> {transposed_Tensor}, size -> {transposed_Tensor.shape}")

Original Tensor -> tensor([[1, 2, 3]]), size -> torch.Size([1, 3])
Transposed Tensor -> tensor([[1],
        [2],
        [3]]), size -> torch.Size([3, 1])


## Aggregations (min, max, sum ...)

In [20]:
## create tensor
x = torch.arange(0, 100, 10)
print(x)
x_min = torch.min(x) # or you can just use x.min() ...ditto for the rest
x_min_position = torch.argmin(x)
x_max = torch.max(x)
x_max_position = torch.argmax(x)
x_mean = torch.mean(x.to(torch.float64)) # note here that mean can not work on integers
x_total = torch.sum(x)
print(f"min -> {x_min}, position -> {x_min_position}, \nmax -> {x_max}, position -> {x_max_position}, \nave -> {x_mean}, \ntotal -> {x_total}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min -> 0, position -> 0, 
max -> 90, position -> 9, 
ave -> 45.0, 
total -> 450


## Reshaping, stacking, squeezing and unsqueezing tensors



*   Reshaping - given an input tensor, change to defined shape
*   View - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* Stacking - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* Squeeze - Squeezes input to remove all the dimenions with value 1.
* UnSqueeze - Returns input with a dimension value of 1 added at dim.
* Permute - Returns a view of the original input with its dimensions permuted (rearranged) to dims



In [21]:
## Reshaping - add an extra dimension
x = torch.arange(1,10)
print(x, x.shape)
## note that new dimensions must be congruent with the shape we want to change or will error, TODO: play around with this
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [22]:
## Change the view
x = torch.arange(1,10)
print(x, x.shape)
# same as reshape, however this shares the same memory as the original tensor, so if you change z then x will change as well
z = x.view(1, 9)
print(z, z.shape)
## example of the mutation carrying on to the original tensor
z[0][3] = 19
print(z, z.shape)
print(x, x.shape) # <- note here that x changed too!

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[ 1,  2,  3, 19,  5,  6,  7,  8,  9]]) torch.Size([1, 9])
tensor([ 1,  2,  3, 19,  5,  6,  7,  8,  9]) torch.Size([9])


In [23]:
## Stack tensors ontop of each other
x = torch.arange(1,10)
print(x, x.shape)
x_stacked = torch.stack([x, x, x], dim=0) # default
print(f"stacked default \n{x_stacked}, size={x_stacked.shape}")
x_stacked = torch.stack([x, x, x], dim=1)
print(f"stacked dim = 1 \n{x_stacked}, size={x_stacked.shape}")

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
stacked default 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]), size=torch.Size([3, 9])
stacked dim = 1 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]), size=torch.Size([9, 3])


In [24]:
## squeeze - removes all single dimensions from a target tensor
print(f"Original -> {x_reshaped} size -> {x_reshaped.shape}")
squeezed = x_reshaped.squeeze()
print(f"Squeezed -> {squeezed} size -> {squeezed.shape}")

Original -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])
Squeezed -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])


In [25]:
## unsqueeze - adds a single dimensions to a target tensor
print(f"Original -> {squeezed} size -> {squeezed.shape}")
unsqueezed = squeezed.unsqueeze(dim=0)
print(f"Unsqueezed -> {unsqueezed} size -> {unsqueezed.shape}")

Original -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])
Unsqueezed -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])


In [26]:
## permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
print(f"original shape -> {x_original.shape}")

## permute the original tensor to reaarange the axis (or dim)
## say you want to permute to color channels, Height, width
x_permuted = x_original.permute(2,0,1) #where 2 was the orginal dim for the color channel and so forth
print(f"Permuted shape -> {x_permuted.shape}")

original shape -> torch.Size([224, 224, 3])
Permuted shape -> torch.Size([3, 224, 224])


## Indexing (selecting data in tensors)

Indexing in pyTorch is similar to Numpy

In [70]:
x = torch.arange(1,10).reshape(1,3,3)
print(f"x -> {x}, \nshape -> {x.shape}, \ntotal dimensions -> {x.ndim}")
## Indexing the tensor, on the first dimension
print(f"\nFirst dimension -> {x[0]}")
print(f"\nFirst dimension, First row -> {x[0][0]}") ## can also be written as x[0,0]
print(f"\nFirst dimension, First row, third element -> {x[0][0][0]}")
print(f"\nFirst dimension, third row, third element -> {x[0][2][2]}")

## You can also use ":" to select all of a target dimension
print(f"\nFirst dimension, second row -> {x[:, 1]}")

## or you can select, all the dimensions upto a certain index of the last
print(f"\nFirst dimension, all rows, all second elements -> {x[:, : ,1]}")

x -> tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]), 
shape -> torch.Size([1, 3, 3]), 
total dimensions -> 3

First dimension -> tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

First dimension, First row -> tensor([1, 2, 3])

First dimension, First row, third element -> 1

First dimension, third row, third element -> 9

First dimension, second row -> tensor([[4, 5, 6]])

First dimension, all rows, all second elements -> tensor([[2, 5, 8]])


## PyTorch tensors and NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

`torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.

`torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [81]:
## Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor ## note that its is using numpy's default datatype on the tensor and not torch's

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [95]:
## Tensor to numpy array
tensor = torch.rand(3)
numPyArr = tensor.numpy()
print(f"tensor -> {tensor} \nNumpy array -> {numPyArr}") ## note the datatype change

tensor -> tensor([0.7383, 0.1515, 0.1907]) 
Numpy array -> [0.7383069  0.15147334 0.19068706]
