<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

In [26]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [27]:
scalar.ndim

0

In [28]:
## Get tensor back as python int
scalar.item()

7

In [29]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [30]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [31]:
MATRIX.ndim

2

In [32]:
MATRIX[1]

tensor([ 9, 10])

In [33]:
vector.shape

torch.Size([2])

In [34]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91]
    ]
    ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 21, 31],
         [41, 51, 61],
         [71, 81, 91]]])

In [35]:
TENSOR.shape

torch.Size([2, 3, 3])

## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [36]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0775, 0.4072, 0.9790, 0.8262],
        [0.6169, 0.3832, 0.5210, 0.9832],
        [0.5922, 0.6071, 0.7480, 0.5259]])

In [37]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.7679, 0.2204, 0.2667],
         [0.6712, 0.5510, 0.6327],
         [0.6917, 0.1306, 0.6881],
         ...,
         [0.1384, 0.4561, 0.3429],
         [0.8507, 0.1783, 0.9894],
         [0.8694, 0.0620, 0.7286]],

        [[0.9102, 0.7591, 0.9905],
         [0.3060, 0.4554, 0.9861],
         [0.4503, 0.6444, 0.3784],
         ...,
         [0.0042, 0.3877, 0.5767],
         [0.9222, 0.3015, 0.4954],
         [0.8423, 0.7242, 0.6916]],

        [[0.3956, 0.6890, 0.1823],
         [0.0914, 0.2748, 0.2319],
         [0.7041, 0.3620, 0.1001],
         ...,
         [0.4761, 0.0729, 0.9503],
         [0.7643, 0.6271, 0.6123],
         [0.1582, 0.8283, 0.4387]],

        ...,

        [[0.9188, 0.5919, 0.8377],
         [0.3840, 0.9332, 0.7163],
         [0.3651, 0.2570, 0.8218],
         ...,
         [0.9249, 0.2811, 0.7715],
         [0.8110, 0.3042, 0.3838],
         [0.8027, 0.4728, 0.0407]],

        [[0.1188, 0.3541, 0.3566],
         [0.2107, 0.5407, 0.5869],
         [0.

In [38]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [39]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [41]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [43]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [44]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [45]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.1519, 0.2126, 0.4529, 0.7204],
        [0.3525, 0.8774, 0.6073, 0.5367],
        [0.7098, 0.3992, 0.5292, 0.5139]])

In [46]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.1519, 0.2126, 0.4529, 0.7204],
        [0.3525, 0.8774, 0.6073, 0.5367],
        [0.7098, 0.3992, 0.5292, 0.5139]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [47]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [48]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])

## Transposing tensors

In [75]:
## Transpose
tensor = torch.tensor([[1,2,3]])
print(f"Original Tensor -> {tensor}, size -> {tensor.shape}")
transposed_Tensor = tensor.T
print(f"Transposed Tensor -> {transposed_Tensor}, size -> {transposed_Tensor.shape}")

Original Tensor -> tensor([[1, 2, 3]]), size -> torch.Size([1, 3])
Transposed Tensor -> tensor([[1],
        [2],
        [3]]), size -> torch.Size([3, 1])


## Aggregations (min, max, sum ...)

In [94]:
## create tensor
x = torch.arange(0, 100, 10)
print(x)
x_min = torch.min(x) # or you can just use x.min() ...ditto for the rest
x_min_position = torch.argmin(x)
x_max = torch.max(x)
x_max_position = torch.argmax(x)
x_mean = torch.mean(x.to(torch.float64)) # note here that mean can not work on integers
x_total = torch.sum(x)
print(f"min -> {x_min}, position -> {x_min_position}, \nmax -> {x_max}, position -> {x_max_position}, \nave -> {x_mean}, \ntotal -> {x_total}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min -> 0, position -> 0, 
max -> 90, position -> 9, 
ave -> 45.0, 
total -> 450
