<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
## Get tensor back as python int
scalar.item()

7

In [5]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
vector.shape

torch.Size([2])

In [10]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91]
    ]
    ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 21, 31],
         [41, 51, 61],
         [71, 81, 91]]])

In [11]:
TENSOR.shape

torch.Size([2, 3, 3])

## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [12]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4164, 0.8787, 0.3142, 0.8191],
        [0.0944, 0.2028, 0.7559, 0.9713],
        [0.6229, 0.4175, 0.2766, 0.2402]])

In [13]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.5851, 0.9189, 0.2746],
         [0.5289, 0.7125, 0.7680],
         [0.9806, 0.4187, 0.9727],
         ...,
         [0.4565, 0.6429, 0.0132],
         [0.7169, 0.3316, 0.3384],
         [0.8370, 0.9231, 0.7771]],

        [[0.6971, 0.9486, 0.0099],
         [0.1875, 0.4820, 0.1702],
         [0.3729, 0.5481, 0.9207],
         ...,
         [0.3280, 0.2789, 0.7089],
         [0.9194, 0.9451, 0.2031],
         [0.8376, 0.0775, 0.4075]],

        [[0.6127, 0.1518, 0.6014],
         [0.0318, 0.6054, 0.1489],
         [0.5804, 0.4498, 0.0399],
         ...,
         [0.5384, 0.0493, 0.3184],
         [0.3327, 0.5209, 0.3818],
         [0.9171, 0.2602, 0.3724]],

        ...,

        [[0.6457, 0.3916, 0.0938],
         [0.0461, 0.3369, 0.6272],
         [0.7378, 0.8064, 0.3459],
         ...,
         [0.5859, 0.2790, 0.9074],
         [0.8503, 0.4540, 0.7087],
         [0.2032, 0.5085, 0.6338]],

        [[0.1842, 0.2612, 0.8246],
         [0.3524, 0.3755, 0.3125],
         [0.

In [14]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [15]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [17]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [19]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [20]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [21]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.3209, 0.4398, 0.4353, 0.9042],
        [0.8179, 0.0561, 0.4139, 0.4729],
        [0.5612, 0.0495, 0.4195, 0.7738]])

In [22]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.3209, 0.4398, 0.4353, 0.9042],
        [0.8179, 0.0561, 0.4139, 0.4729],
        [0.5612, 0.0495, 0.4195, 0.7738]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [33]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [37]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])