<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

## Understanding Scalars, vectors, matrices and tensors

In [2]:
#scalar
scalar = torch.tensor(7)
print(f"scalar = { scalar } \nndim -> {scalar.ndim} shape -> {scalar.shape} item -> {scalar.item()}")

scalar = 7 
ndim -> 0 shape -> torch.Size([]) item -> 7


In [3]:
## Vector
vector = torch.tensor([7,7])
print(f"Vector = { vector } \nndim -> {vector.ndim} shape -> {vector.shape}")

Vector = tensor([7, 7]) 
ndim -> 1 shape -> torch.Size([2])


In [4]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
print(f"Matrix = { MATRIX } \nndim -> {MATRIX.ndim} shape -> {MATRIX.shape}")

Matrix = tensor([[ 7,  8],
        [ 9, 10]]) 
ndim -> 2 shape -> torch.Size([2, 2])


The torch.size indicates the shape of a tensor, and describes the number of elements along each dimension. In the case of a tensor t with shape (2, 4, 3) as below, it means that the tensor has 3 dimensions, with the first dimension having a size of 2, the second dimension having a size of 4, and the third dimension having a size of 3. In other words, the tensor has 2 rows, each row has 4 columns, and each column has 3 elements. The total number of elements in the tensor is the product of the sizes of all dimensions, which in this case is 2 * 4 * 3 = 24

So maybe one way to think of 3 dimensions is as a cube with height (2), width (4) and depth (3)... but any more additional dims will be hard to mentally picture

In [5]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91],
        [101,111,121]
    ]
    ])
print(f"Tensor = { TENSOR } \nndim -> {TENSOR.ndim} shape -> {TENSOR.shape} totalElements -> {TENSOR.numel()}")

Tensor = tensor([[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9],
         [ 10,  11,  12]],

        [[ 11,  21,  31],
         [ 41,  51,  61],
         [ 71,  81,  91],
         [101, 111, 121]]]) 
ndim -> 3 shape -> torch.Size([2, 4, 3]) totalElements -> 24


## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [6]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7960, 0.8682, 0.8200, 0.8467],
        [0.1953, 0.9351, 0.2288, 0.5013],
        [0.6399, 0.1773, 0.6210, 0.7300]])

In [7]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.2458, 0.8878, 0.7328],
         [0.1752, 0.3993, 0.2507],
         [0.9838, 0.3927, 0.6350],
         ...,
         [0.2627, 0.5001, 0.4313],
         [0.1839, 0.1909, 0.2311],
         [0.9612, 0.7273, 0.8706]],

        [[0.9192, 0.3122, 0.7678],
         [0.7934, 0.4255, 0.7035],
         [0.3381, 0.8226, 0.9669],
         ...,
         [0.2553, 0.0768, 0.8582],
         [0.7263, 0.4204, 0.3565],
         [0.7815, 0.5095, 0.2147]],

        [[0.3982, 0.1567, 0.5307],
         [0.9395, 0.5204, 0.9948],
         [0.5618, 0.3578, 0.1681],
         ...,
         [0.2295, 0.9426, 0.2404],
         [0.3643, 0.6826, 0.1540],
         [0.5064, 0.4540, 0.0720]],

        ...,

        [[0.1040, 0.2384, 0.5649],
         [0.4340, 0.0021, 0.1315],
         [0.2439, 0.7396, 0.0578],
         ...,
         [0.5651, 0.2790, 0.7116],
         [0.6106, 0.0576, 0.0555],
         [0.3293, 0.1881, 0.1770]],

        [[0.6056, 0.1359, 0.6949],
         [0.6947, 0.5204, 0.7414],
         [0.

In [8]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [9]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [11]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [13]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [14]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [15]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.1759, 0.5392, 0.6181, 0.5256],
        [0.3218, 0.2958, 0.1035, 0.4166],
        [0.9827, 0.4059, 0.2857, 0.7792]])

In [16]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.1759, 0.5392, 0.6181, 0.5256],
        [0.3218, 0.2958, 0.1035, 0.4166],
        [0.9827, 0.4059, 0.2857, 0.7792]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [18]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])

## Transposing tensors

In [19]:
## Transpose
tensor = torch.tensor([[1,2,3]])
print(f"Original Tensor -> {tensor}, size -> {tensor.shape}")
transposed_Tensor = tensor.T
print(f"Transposed Tensor -> {transposed_Tensor}, size -> {transposed_Tensor.shape}")

Original Tensor -> tensor([[1, 2, 3]]), size -> torch.Size([1, 3])
Transposed Tensor -> tensor([[1],
        [2],
        [3]]), size -> torch.Size([3, 1])


## Aggregations (min, max, sum ...)

In [20]:
## create tensor
x = torch.arange(0, 100, 10)
print(x)
x_min = torch.min(x) # or you can just use x.min() ...ditto for the rest
x_min_position = torch.argmin(x)
x_max = torch.max(x)
x_max_position = torch.argmax(x)
x_mean = torch.mean(x.to(torch.float64)) # note here that mean can not work on integers
x_total = torch.sum(x)
print(f"min -> {x_min}, position -> {x_min_position}, \nmax -> {x_max}, position -> {x_max_position}, \nave -> {x_mean}, \ntotal -> {x_total}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min -> 0, position -> 0, 
max -> 90, position -> 9, 
ave -> 45.0, 
total -> 450


## Reshaping, stacking, squeezing and unsqueezing tensors



*   Reshaping - given an input tensor, change to defined shape
*   View - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* Stacking - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* Squeeze - Squeezes input to remove all the dimenions with value 1.
* UnSqueeze - Returns input with a dimension value of 1 added at dim.
* Permute - Returns a view of the original input with its dimensions permuted (rearranged) to dims



In [21]:
## Reshaping - add an extra dimension
x = torch.arange(1,10)
print(x, x.shape)
## note that new dimensions must be congruent with the shape we want to change or will error, TODO: play around with this
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [22]:
## Change the view
x = torch.arange(1,10)
print(x, x.shape)
# same as reshape, however this shares the same memory as the original tensor, so if you change z then x will change as well
z = x.view(1, 9)
print(z, z.shape)
## example of the mutation carrying on to the original tensor
z[0][3] = 19
print(z, z.shape)
print(x, x.shape) # <- note here that x changed too!

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[ 1,  2,  3, 19,  5,  6,  7,  8,  9]]) torch.Size([1, 9])
tensor([ 1,  2,  3, 19,  5,  6,  7,  8,  9]) torch.Size([9])


In [23]:
## Stack tensors ontop of each other
x = torch.arange(1,10)
print(x, x.shape)
x_stacked = torch.stack([x, x, x], dim=0) # default
print(f"stacked default \n{x_stacked}, size={x_stacked.shape}")
x_stacked = torch.stack([x, x, x], dim=1)
print(f"stacked dim = 1 \n{x_stacked}, size={x_stacked.shape}")

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
stacked default 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]), size=torch.Size([3, 9])
stacked dim = 1 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]), size=torch.Size([9, 3])


In [29]:
## squeeze - removes all single dimensions from a target tensor
print(f"Original -> {x_reshaped} size -> {x_reshaped.shape}")
squeezed = x_reshaped.squeeze()
print(f"Squeezed -> {squeezed} size -> {squeezed.shape}")

Original -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])
Squeezed -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])


In [36]:
## unsqueeze - adds a single dimensions to a target tensor
print(f"Original -> {squeezed} size -> {squeezed.shape}")
unsqueezed = squeezed.unsqueeze(dim=0)
print(f"Unsqueezed -> {unsqueezed} size -> {unsqueezed.shape}")

Original -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])
Unsqueezed -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])


In [41]:
## permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
print(f"original shape -> {x_original.shape}")

## permute the original tensor to reaarange the axis (or dim)
## say you want to permute to color channels, Height, width
x_permuted = x_original.permute(2,0,1) #where 2 was the orginal dim for the color channel and so forth
print(f"Permuted shape -> {x_permuted.shape}")

original shape -> torch.Size([224, 224, 3])
Permuted shape -> torch.Size([3, 224, 224])


## Indexing (selecting data in tensors)

Indexing in pyTorch is similar to Numpy