<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

## Understanding Scalars, vectors, matrices and tensors

In [2]:
#scalar
scalar = torch.tensor(7)
print(f"scalar = { scalar } \nndim -> {scalar.ndim} shape -> {scalar.shape} item -> {scalar.item()}")

scalar = 7 
ndim -> 0 shape -> torch.Size([]) item -> 7


In [3]:
## Vector
vector = torch.tensor([7,7])
print(f"Vector = { vector } \nndim -> {vector.ndim} shape -> {vector.shape}")

Vector = tensor([7, 7]) 
ndim -> 1 shape -> torch.Size([2])


In [4]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
print(f"Matrix = { MATRIX } \nndim -> {MATRIX.ndim} shape -> {MATRIX.shape}")

Matrix = tensor([[ 7,  8],
        [ 9, 10]]) 
ndim -> 2 shape -> torch.Size([2, 2])


The torch.size indicates the shape of a tensor, and describes the number of elements along each dimension. In the case of a tensor t with shape (2, 4, 3) as below, it means that the tensor has 3 dimensions, with the first dimension having a size of 2, the second dimension having a size of 4, and the third dimension having a size of 3. In other words, the tensor has 2 rows, each row has 4 columns, and each column has 3 elements. The total number of elements in the tensor is the product of the sizes of all dimensions, which in this case is 2 * 4 * 3 = 24

So maybe one way to think of 3 dimensions is as a cube with height (2), width (4) and depth (3)... but any more additional dims will be hard to mentally picture

In [5]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91],
        [101,111,121]
    ]
    ])
print(f"Tensor = { TENSOR } \nndim -> {TENSOR.ndim} shape -> {TENSOR.shape} totalElements -> {TENSOR.numel()}")

Tensor = tensor([[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9],
         [ 10,  11,  12]],

        [[ 11,  21,  31],
         [ 41,  51,  61],
         [ 71,  81,  91],
         [101, 111, 121]]]) 
ndim -> 3 shape -> torch.Size([2, 4, 3]) totalElements -> 24


## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [6]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1361, 0.8305, 0.5345, 0.6264],
        [0.7558, 0.5776, 0.9246, 0.3991],
        [0.1151, 0.1537, 0.0799, 0.2784]])

In [7]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[0.3380, 0.4000, 0.6832],
         [0.1615, 0.0912, 0.7950],
         [0.8454, 0.6488, 0.1745],
         ...,
         [0.8825, 0.6653, 0.7626],
         [0.0619, 0.3041, 0.3764],
         [0.5176, 0.7306, 0.4461]],

        [[0.4949, 0.7145, 0.8369],
         [0.1128, 0.7711, 0.5600],
         [0.6321, 0.7264, 0.4214],
         ...,
         [0.7661, 0.3918, 0.2580],
         [0.6514, 0.4240, 0.7346],
         [0.5534, 0.8329, 0.7834]],

        [[0.8049, 0.1664, 0.4045],
         [0.0169, 0.6773, 0.8870],
         [0.0923, 0.4141, 0.4984],
         ...,
         [0.8306, 0.7839, 0.0767],
         [0.9087, 0.4500, 0.0129],
         [0.1748, 0.1398, 0.2619]],

        ...,

        [[0.0256, 0.9906, 0.9303],
         [0.2985, 0.9062, 0.4345],
         [0.9142, 0.9572, 0.5837],
         ...,
         [0.4762, 0.0896, 0.1297],
         [0.2442, 0.6554, 0.2984],
         [0.7830, 0.7635, 0.1801]],

        [[0.2127, 0.1829, 0.9748],
         [0.1597, 0.0090, 0.6963],
         [0.

In [8]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [9]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [11]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [13]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [14]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

### Getting Information from tensors



1.   Tensors not the right data type - get data type `tensor.dtype`
2.   Tensors not the right shape - get shape `tensor.shape`
3.   Tensors not the right device - get shape `tensor.device`




In [15]:
# create a tensor
some_Tensor = torch.rand(3,4)
some_Tensor

tensor([[0.1112, 0.0651, 0.3835, 0.2691],
        [0.0813, 0.6969, 0.7429, 0.3186],
        [0.1004, 0.2341, 0.9461, 0.7249]])

In [16]:
# Find out details of a tensor
some_Tensor = some_Tensor.to(torch.float64)
print(some_Tensor)
print(f"Data type of tensor: {some_Tensor.dtype}")
print(f"Shape of tensor: {some_Tensor.shape}")
print(f"Device of tensor: {some_Tensor.device}")

tensor([[0.1112, 0.0651, 0.3835, 0.2691],
        [0.0813, 0.6969, 0.7429, 0.3186],
        [0.1004, 0.2341, 0.9461, 0.7249]], dtype=torch.float64)
Data type of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operations)
Addition

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
# Addition
tensor = torch.tensor([1,2,3])
print(tensor + 15)
# Subtract
print(tensor -10)
# Multiply
print(tensor * 10)
# divide
print(tensor/2)
# matrix multiply (dot product)
matrix_to_multiply = torch.tensor([[1],[2],[3]])
torch.matmul(tensor, matrix_to_multiply) # (1*1 + 2*2 + 3*3)

tensor([16, 17, 18])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


tensor([14])

In [18]:
## example of dot product from here https://www.mathsisfun.com/algebra/matrix-multiplying.html but using pytorch
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(a,b)
## note that matmul is way faster than using a traditional for loop
## as in any dot product calculation number of rows of a == number columns of b

tensor([[ 58,  64],
        [139, 154]])

## Transposing tensors

In [19]:
## Transpose
tensor = torch.tensor([[1,2,3]])
print(f"Original Tensor -> {tensor}, size -> {tensor.shape}")
transposed_Tensor = tensor.T
print(f"Transposed Tensor -> {transposed_Tensor}, size -> {transposed_Tensor.shape}")

Original Tensor -> tensor([[1, 2, 3]]), size -> torch.Size([1, 3])
Transposed Tensor -> tensor([[1],
        [2],
        [3]]), size -> torch.Size([3, 1])


## Aggregations (min, max, sum ...)

In [20]:
## create tensor
x = torch.arange(0, 100, 10)
print(x)
x_min = torch.min(x) # or you can just use x.min() ...ditto for the rest
x_min_position = torch.argmin(x)
x_max = torch.max(x)
x_max_position = torch.argmax(x)
x_mean = torch.mean(x.to(torch.float64)) # note here that mean can not work on integers
x_total = torch.sum(x)
print(f"min -> {x_min}, position -> {x_min_position}, \nmax -> {x_max}, position -> {x_max_position}, \nave -> {x_mean}, \ntotal -> {x_total}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min -> 0, position -> 0, 
max -> 90, position -> 9, 
ave -> 45.0, 
total -> 450


## Reshaping, stacking, squeezing and unsqueezing tensors



*   Reshaping - given an input tensor, change to defined shape
*   View - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* Stacking - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* Squeeze - Squeezes input to remove all the dimenions with value 1.
* UnSqueeze - Returns input with a dimension value of 1 added at dim.
* Permute - Returns a view of the original input with its dimensions permuted (rearranged) to dims



In [21]:
## Reshaping - add an extra dimension
x = torch.arange(1,10)
print(x, x.shape)
## note that new dimensions must be congruent with the shape we want to change or will error, TODO: play around with this
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [22]:
## Change the view
x = torch.arange(1,10)
print(x, x.shape)
# same as reshape, however this shares the same memory as the original tensor, so if you change z then x will change as well
z = x.view(1, 9)
print(z, z.shape)
## example of the mutation carrying on to the original tensor
z[0][3] = 19
print(z, z.shape)
print(x, x.shape) # <- note here that x changed too!

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[ 1,  2,  3, 19,  5,  6,  7,  8,  9]]) torch.Size([1, 9])
tensor([ 1,  2,  3, 19,  5,  6,  7,  8,  9]) torch.Size([9])


In [23]:
## Stack tensors ontop of each other
x = torch.arange(1,10)
print(x, x.shape)
x_stacked = torch.stack([x, x, x], dim=0) # default
print(f"stacked default \n{x_stacked}, size={x_stacked.shape}")
x_stacked = torch.stack([x, x, x], dim=1)
print(f"stacked dim = 1 \n{x_stacked}, size={x_stacked.shape}")

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
stacked default 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]), size=torch.Size([3, 9])
stacked dim = 1 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]), size=torch.Size([9, 3])


In [24]:
## squeeze - removes all single dimensions from a target tensor
print(f"Original -> {x_reshaped} size -> {x_reshaped.shape}")
squeezed = x_reshaped.squeeze()
print(f"Squeezed -> {squeezed} size -> {squeezed.shape}")

Original -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])
Squeezed -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])


In [25]:
## unsqueeze - adds a single dimensions to a target tensor
print(f"Original -> {squeezed} size -> {squeezed.shape}")
unsqueezed = squeezed.unsqueeze(dim=0)
print(f"Unsqueezed -> {unsqueezed} size -> {unsqueezed.shape}")

Original -> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) size -> torch.Size([9])
Unsqueezed -> tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) size -> torch.Size([1, 9])


In [26]:
## permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
print(f"original shape -> {x_original.shape}")

## permute the original tensor to reaarange the axis (or dim)
## say you want to permute to color channels, Height, width
x_permuted = x_original.permute(2,0,1) #where 2 was the orginal dim for the color channel and so forth
print(f"Permuted shape -> {x_permuted.shape}")

original shape -> torch.Size([224, 224, 3])
Permuted shape -> torch.Size([3, 224, 224])


## Indexing (selecting data in tensors)

Indexing in pyTorch is similar to Numpy

In [27]:
x = torch.arange(1,10).reshape(1,3,3)
print(f"x -> {x}, \nshape -> {x.shape}, \ntotal dimensions -> {x.ndim}")
## Indexing the tensor, on the first dimension
print(f"\nFirst dimension -> {x[0]}")
print(f"\nFirst dimension, First row -> {x[0][0]}") ## can also be written as x[0,0]
print(f"\nFirst dimension, First row, third element -> {x[0][0][0]}")
print(f"\nFirst dimension, third row, third element -> {x[0][2][2]}")

## You can also use ":" to select all of a target dimension
print(f"\nFirst dimension, second row -> {x[:, 1]}")

## or you can select, all the dimensions upto a certain index of the last
print(f"\nFirst dimension, all rows, all second elements -> {x[:, : ,1]}")

x -> tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]), 
shape -> torch.Size([1, 3, 3]), 
total dimensions -> 3

First dimension -> tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

First dimension, First row -> tensor([1, 2, 3])

First dimension, First row, third element -> 1

First dimension, third row, third element -> 9

First dimension, second row -> tensor([[4, 5, 6]])

First dimension, all rows, all second elements -> tensor([[2, 5, 8]])


## PyTorch tensors and NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

`torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.

`torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [28]:
## Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor ## note that its is using numpy's default datatype on the tensor and not torch's

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [29]:
## Tensor to numpy array
tensor = torch.rand(3)
numPyArr = tensor.numpy()
print(f"tensor -> {tensor} \nNumpy array -> {numPyArr}") ## note the datatype change

tensor -> tensor([0.3188, 0.7726, 0.6359]) 
Numpy array -> [0.31881148 0.7726105  0.635903  ]


## Reproducibiity (trying to take the random out of random )
For more detail see here: https://pytorch.org/docs/stable/notes/randomness.html#reproducibility

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to make a better fit of the data -> Rinse repeat...`

To reduce the randomness in nueral networks and pyTorch, the concept of **Random seed** comes in

An explanation from bing chat on what a random seed is:

> A random seed is a **starting point** in generating random numbers. It specifies the start point when a computer generates a random number sequence ². This can be any number, but it usually comes from seconds on a computer system’s clock ². A random seed is used to initialize a pseudorandom number generator ¹. The sequence of numbers generated by the pseudorandom number generator is completely determined by the seed, so if it is reinitialized with the same seed, it will produce the same sequence of numbers ¹.

*Source: Conversation with Bing, 7/19/2023
(1) Random Seed: Definition - Statistics How To. https://www.statisticshowto.com/random-seed-definition/.
(2) Random seed - Wikipedia. https://en.wikipedia.org/wiki/Random_seed.
(3) The story behind ‘random.seed(42)’ in machine learning. https://medium.com/geekculture/the-story-behind-random-seed-42-in-machine-learning-b838c4ac290a.*







In [32]:
## Examples, say you have two random generated tensors, naturally it would be very unlikely for them to be equal..
import torch
rand_tensor_x = torch.rand(2,3)
rand_tensor_y = torch.rand(2,3)
print(rand_tensor_x)
print(rand_tensor_y)
print(f"Are the tensors equal ? -> {rand_tensor_x == rand_tensor_y}")

## but now set a Random seed
RAND_SEED = 42 # can be anything really
torch.manual_seed(RAND_SEED)
rand_tensor_u = torch.rand(2,3)
torch.manual_seed(RAND_SEED) # note that you have to set the seed every time BEFORE you generate the numbers!
rand_tensor_v = torch.rand(2,3)
print(rand_tensor_u)
print(rand_tensor_v)
print(f"Are the tensors equal now ? -> {rand_tensor_u == rand_tensor_v}")

tensor([[0.0873, 0.0595, 0.6177],
        [0.0947, 0.3213, 0.4410]])
tensor([[0.0567, 0.8188, 0.3860],
        [0.7521, 0.3172, 0.8480]])
Are the tensors equal ? -> tensor([[False, False, False],
        [False, False, False]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Are the tensors equal now ? -> tensor([[True, True, True],
        [True, True, True]])


## Running Tensors and pytorch objects on the GPUs and making faster computations

GPUs = Faster computation of numbers, thanks to CUDA + NVIDIA hardware + pyTorch

*Taken from the notes section of tutorial below*
### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.
Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.
> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [1]:
## already covered this, but to see if you are running on gpu change the run type above, if you are not you will simply get a command not found...
!nvidia-smi

Wed Jul 19 09:09:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###2. Getting PyTorch to run on the GPU

In [3]:
## You can also check for GPU access with pyTorch
import torch
torch.cuda.is_available()

True

In [10]:
# setup device agnostic code
# see here if you writing scripts and not using google colab https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code
device = "cuda" if torch.cuda.is_available() else "cpu"
device ## will see where can use device as a variable later

'cuda'

In [6]:
# Count the # of devices
torch.cuda.device_count()

1

###3. Putting tensors (and models) on the GPU and back on the CPU

In [15]:
## by default tensors are created on a cpu
tensor = torch.tensor([1,2,3])
print(f"device of tensor --> {tensor.device}")
## but you can move it to a gpu by using the device variable we created above and reassigning to new tensor
tensor_on_gpu = tensor.to(device = device)
print(f"device of tensor --> {tensor_on_gpu.device}")
## but sometimes you want to flip back onto cpu, for ex if you want to do a numpy calculation

tensor_on_gpu.cpu().numpy() ## note here that hadn't you used the cpu method before invoking numpy it would error out...

device of tensor --> cpu
device of tensor --> cuda:0


array([1, 2, 3])