<a href="https://colab.research.google.com/github/Dereje1/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

Creating tensors

Pytorch tensors are created with torch.tensor() -> reference -> https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
## Get tensor back as python int
scalar.item()

7

In [ ]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
## MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [11,21,31],
        [41,51,61],
        [71,81,91]
    ]
    ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 21, 31],
         [41, 51, 61],
         [71, 81, 91]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

## Random Tensors

Why Random tensors ?

Random tensors are important since the way many nueral networks learn is by starting with a matix of random numbers and then iterate over those numbers to fit the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
## Create random tensors with pytorch of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2703, 0.7000, 0.5504, 0.1923],
        [0.1583, 0.3207, 0.0966, 0.4959],
        [0.9159, 0.9651, 0.6443, 0.6411]])

In [46]:
## Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channel (R,G,B)
random_image_size_tensor

tensor([[[1.8442e-01, 4.9374e-02, 8.3410e-01],
         [9.0698e-01, 9.3133e-03, 9.3478e-01],
         [7.0622e-02, 9.4696e-01, 4.2378e-01],
         ...,
         [6.8506e-01, 9.0543e-01, 3.0695e-01],
         [3.4081e-01, 6.0469e-01, 9.9227e-01],
         [1.2111e-01, 7.9372e-01, 2.9272e-01]],

        [[7.8611e-02, 3.3113e-01, 7.7216e-02],
         [3.5583e-02, 3.1197e-01, 9.2296e-02],
         [2.2099e-01, 3.7323e-01, 7.3080e-01],
         ...,
         [7.2465e-01, 6.9891e-01, 5.3312e-01],
         [7.0707e-01, 3.9910e-01, 3.4822e-01],
         [2.7469e-01, 4.3633e-01, 5.8948e-01]],

        [[7.5332e-01, 4.0006e-01, 1.7162e-03],
         [1.9735e-04, 8.5521e-01, 9.3541e-01],
         [1.1121e-01, 5.7538e-01, 7.6724e-01],
         ...,
         [4.7940e-01, 7.1352e-01, 8.1438e-01],
         [9.8942e-01, 9.9128e-01, 5.4623e-01],
         [8.2131e-01, 4.5077e-01, 6.8932e-01]],

        ...,

        [[8.3432e-01, 4.2809e-01, 1.5785e-01],
         [7.0133e-02, 1.4441e-01, 4.6165e-01]

In [47]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [51]:
## Create a tensor of all zeroes and ones
zeroes = torch.zeros(3,4)
ones=torch.ones(3,4)
zeroes
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
zeroes.dtype

torch.float32

## creating a range of tensors and tensors-like

In [59]:
one_to_ten = torch.arange(1, 11, 1) # third arg is step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
## Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [79]:
#Float 32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype the tensor is default is float32 -> adjust precision with memory/perf tradeoff
                               device=None, # default is 'cpu', the device the tensor is on
                               requires_grad=False) # track 'gradients' (or not)
float_16_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=torch.float16)

float_32_tensor.dtype


torch.float32

In [80]:
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)